import localFont from "next/font/local";
import "./globals.css";

import { Plus_Jakarta_Sans } from "next/font/google";
import { TWKEverett } from "./fonts/fonts";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

const polySans = localFont({
  src: "./fonts/PolySansMedian.woff",
  variable: "--font-polysans-median",
  // weight: "100 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Katia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${TWKEverett.variable} ${plusJakartaSans.className} ${polySans.variable} antialiased bg-[#101016]`}
      >
        {children}
      </body>
    </html>
  );
}
