import localFont from "next/font/local";
import "./globals.css";

import { ReduxStoreProvider } from "@/providers/ReduxProvider";
import { Plus_Jakarta_Sans } from "next/font/google";
import { inter, ProximaNova, TWKEverett } from "./fonts/fonts";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "sonner";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

const polySans = localFont({
  src: "./fonts/PolySansMedian.woff",
  variable: "--font-polysans-median",
  // weight: "100 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Katia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${TWKEverett.variable} ${inter.variable} ${ProximaNova.variable} ${plusJakartaSans.className} ${polySans.variable} antialiased bg-[#101016]`}
      >
        <Toaster richColors position="bottom-center" />
        <ReactQueryProvider>
          <ReduxStoreProvider>{children}</ReduxStoreProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
